#!/bin/bash

echo "Post install script is running now."

echo -e "Execute the following lines to activate the program:\n" \
        "\systemctl enable cage@tty1.service;\n" \
        "\tln -s /etc/systemd/system/default.target /usr/lib/systemd/system/graphical.target;\n"
