#!/bin/bash

echo "Post install script is running now."

ln -s /etc/systemd/system/cage@.service /etc/systemd/system/graphical.target.wants/cage@tty1.service;

ln -s /etc/systemd/system/default.target /usr/lib/systemd/system/graphical.target;
